AWSTempalteFormatVersion : 2010-09-09
Description: Development Environment For Grover Pi-Hole.

Parameters:
  KeyName:
    Description: KeyPair to allow SSH access.
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: Instance Type For Dev Instance
    AllowedValues:
      t2.nano
      t2.micro
      t2.small

Resources:
  